[package]
name = "cstar"
description = "An ECS-based C-style language"
author = "Benjamin Lefebvre"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = "2"
lazy_static = "1"
pest = "2"
pest_derive = "2"